add api docs

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -61,6 +61,14 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install enchant-2  # for spell checking
+      - name: Build API docs
+        run: |
+          hatch run docs:api
+          # If this fails run `hatch run docs:api` locally
+          # and commit.
+          git status --porcelain
+          git status -s | grep -e "M" && exit 1
+          git status -s | grep -e "A" && exit 1
       - run: hatch run docs:build
 
   test_lint:
